'use strict';

// tests for authorizerFunc
// Generated by serverless-jest-plugin

const mod = require('./../src/ath/ath_handler');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'auth' });

describe('authorizerFunc', () => {
  beforeAll(done => {
    //  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then(response => {
      expect(response).toBeDefined();
    });
  });
});
