'use strict';

// tests for getByIdAndDate
// Generated by serverless-jest-plugin

const mod = require('./../src/crm_handler');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'getByIdAndDate' });

describe('getByIdAndDate', () => {
  beforeAll(done => {
    //  lambdaWrapper.init(liveFunction); // Run the deployed lambda
    //need to load request data....
    //how do we do multiple data sets
    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then(response => {
      expect(response).toBeDefined();
    });
  });
});
